### ISSUE TITLE
web2py_osx error on Sierra (OSX 10.12)

### ISSUE THREAD

**Issue by discohead** [web2py/web2py#1551]
I'm on macOS 10.12.1

I downloaded the web2py app from http://www.web2py.com/examples/static/web2py_osx.zip

When I try to run it, I get this web2py error dialog: http://take.ms/IIXG5

Here are the details from the console: http://take.ms/tTTgG

"Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once."

**Comment by discohead** [comment]
FWIW, I've since upgraded to macOS 10.12.2 and this error remains.

**Comment by abaric** [comment]
Any progress on this??

**Comment by lcolmen** [comment]
Well as 16 september 2017, I get the same error using Sierra (OSX 10.12.6)

**Comment by leonelcamara** [comment]
Appears to be a [py2app bug](https://bitbucket.org/ronaldoussoren/py2app/issues/232/py2app-tk-app-fails-with-detected-missing), I would simply use the source version while the problem persists.

**Comment by mkmkulam** [comment]
Hello. As of Aug. 14th 2018 the problem with web2py.app persists.
I am on a Mac Powerbook with macOS High Sierra v. 10.13.6
The source version works just fine.

**Comment by JasonCrowe** [comment]
I have this same problem.

I am fine using the source as Bogdan mentioned, but maybe the compiled version should be pulled from the website if it doesn't work after 2+ years?

**Comment by BogdanOleksyshyn** [comment]
I think it would be better just to switch framework that you are using))) to Django for example.

**Comment by leonelcamara** [comment]
@BogdanOleksyshyn actually web2py should probably just stop distributing .app or .exe versions, they're a small convenience for first time users that make little sense in the python world and cause this kind of problems. Either way this problem is being fixed with pyinstaller by @nicozanf.

See:
https://github.com/nicozanf/web2py-pyinstaller

**Comment by Appsorwebs** [comment]
Been having this web2py Error after installing web2py on my Mac. It won't open in localhost but rather in mac console! I have uninstalled Mamp from my Mac & still it's still showing error.

**Comment by nicozanf** [comment]
I think this can be closed, see #2300
